# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BUILD PROD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and npm run build
      run: |
          npm i
          npm run build -- -c production
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: deploy_dist
        path: dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Download build
        uses: actions/download-artifact@v3.0.0
        with:
          name: deploy_dist
          path: .
      - name: cmd run
        run: ls -la
      - name: cmd run 2
        run: vulnrepo-app;ls -la
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: 'vulnrepo-app'
          destination-github-username: 'kac89'
          destination-repository-name: 'pgrelease'
          target-branch: main
